'use client';
import { useCallback, useEffect, useState } from 'react';
import { useTonAddress, useTonConnectUI, useTonWallet } from '@tonconnect/ui-react';
import { AlertCircle, Check, Copy, ExternalLink, FileCode, Loader2, RefreshCw, Save, Wallet } from 'lucide-react';
import { useAuth } from '../../../providers';
import { api, apiError, type AdminSettings, type ContractDeployment } from '@/lib/api';

export default function AdminSettingsPage() {
  const { token } = useAuth();
  const [tonConnectUI] = useTonConnectUI();
  const address = useTonAddress();
  const wallet = useTonWallet();
  const [settings,setSettings]=useState<AdminSettings>({receivingWallet:'',tonNetwork:'testnet',contractAddress:'',collectorAddress:'',contractVersion:'3.0.0',exchangeRateSource:''});
  const [contracts,setContracts]=useState<ContractDeployment[]>([]); const [walletInput,setWalletInput]=useState('');
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  const load=useCallback(async()=>{try{setLoading(true);setError('');const [s,c]=await Promise.all([api.getAdminSettings(),api.getContracts()]);setSettings(s.settings);setWalletInput(s.settings.receivingWallet);setContracts(c.contracts);}catch(e){setError(apiError(e,'Could not load settings'));}finally{setLoading(false);}},[]);
  useEffect(()=>{if(token) void load();},[token,load]);
  const useConnected=async()=>{if(!wallet){await tonConnectUI.openModal();return;} if(address)setWalletInput(address);};
  const save=async()=>{if(!walletInput){setError('Enter or connect the YIRS revenue wallet');return;}setSaving(true);setError('');setSuccess('');try{await api.updateReceivingWallet(walletInput);setSettings(v=>({...v,receivingWallet:walletInput}));setSuccess('Revenue wallet updated successfully');}catch(e){setError(apiError(e,'Failed to save the revenue wallet'));}finally{setSaving(false);}};
  const prepare=async()=>{setError('');setSuccess('');try{await api.prepareContractDeployment('RevenueCollector',{ownerAddress:walletInput||settings.receivingWallet,revenueWallet:walletInput||settings.receivingWallet});setSuccess('Deployment record prepared. Run the RevenueCollector testnet deployment script to create the on-chain contract.');await load();}catch(e){setError(apiError(e,'Failed to prepare deployment'));}};
  const copy=(v:string)=>{void navigator.clipboard.writeText(v);setSuccess('Copied to clipboard');setTimeout(()=>setSuccess(''),1500);};
  if(loading)return <div className="flex items-center justify-center py-20"><div className="spinner h-12 w-12"/></div>;
  return <div className="mx-auto max-w-4xl p-6 space-y-6">
    {error&&<div className="flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700 dark:border-red-800 dark:bg-red-900/20 dark:text-red-300"><AlertCircle className="h-5 w-5"/>{error}</div>}
    {success&&<div className="flex gap-3 rounded-xl border border-green-200 bg-green-50 p-4 text-green-700 dark:border-green-800 dark:bg-green-900/20 dark:text-green-300"><Check className="h-5 w-5"/>{success}</div>}
    <section className="rounded-2xl bg-white p-6 shadow-sm dark:bg-gray-800"><div className="mb-5 flex items-center gap-3"><Wallet className="h-6 w-6 text-primary-500"/><h2 className="text-xl font-bold">YIRS Revenue Wallet</h2></div><p className="mb-4 text-gray-600 dark:text-gray-300">This is the destination wallet for state tax, levy, fee and other revenue payments processed through the smart contract.</p><div className="space-y-4"><div className="flex gap-3"><input value={walletInput} onChange={e=>setWalletInput(e.target.value)} className="input-primary flex-1 font-mono text-sm" placeholder="TON testnet wallet address"/><button onClick={useConnected} className="btn-ton whitespace-nowrap">{wallet?'Use connected':'Connect wallet'}</button></div>{settings.receivingWallet&&<div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-700"><p className="mb-1 text-sm text-gray-500">Current revenue wallet</p><div className="flex items-center gap-2"><p className="break-all font-mono text-sm">{settings.receivingWallet}</p><button onClick={()=>copy(settings.receivingWallet)}><Copy className="h-4 w-4"/></button></div></div>}<button onClick={save} disabled={saving||!walletInput} className="btn-primary inline-flex items-center gap-2">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>} Save revenue wallet</button></div></section>
    <section className="rounded-2xl bg-white p-6 shadow-sm dark:bg-gray-800"><div className="mb-5 flex items-center gap-3"><FileCode className="h-6 w-6 text-primary-500"/><h2 className="text-xl font-bold">RevenueCollector Contract</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-700"><p className="text-sm text-gray-500">Network</p><p className="font-semibold">{settings.tonNetwork}</p></div><div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-700"><p className="text-sm text-gray-500">Contract version</p><p className="font-semibold">{settings.contractVersion}</p></div></div><p className="mt-4 text-gray-600 dark:text-gray-300">A fresh RevenueCollector deployment is required for the direct YIRS revenue-payment model.</p><button onClick={prepare} className="btn-primary mt-4 inline-flex items-center gap-2"><FileCode className="h-5 w-5"/> Prepare deployment record</button></section>
    <section className="rounded-2xl bg-white p-6 shadow-sm dark:bg-gray-800"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><FileCode className="h-6 w-6 text-primary-500"/><h2 className="text-xl font-bold">Contract deployments</h2></div><button onClick={()=>void load()}><RefreshCw className="h-5 w-5"/></button></div>{contracts.length? <div className="space-y-3">{contracts.map(c=><div key={c.id} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-700"><div className="flex items-center justify-between"><p className="font-semibold">{c.contractType}</p><span className={`badge ${c.status==='deployed'?'badge-success':'badge-warning'}`}>{c.status}</span></div><div className="mt-2 flex items-center gap-2"><p className="break-all font-mono text-sm text-gray-600 dark:text-gray-300">{c.address||'Not deployed'}</p>{c.address&&<><button onClick={()=>copy(c.address!)}><Copy className="h-4 w-4"/></button><a href={`https://testnet.tonviewer.com/${c.address}`} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/></a></>}</div><p className="mt-2 text-xs text-gray-500">{c.network}</p></div>)}</div>:<p className="py-8 text-center text-gray-500">No deployment records yet.</p>}</section>
  </div>;
}
